name: FoxUtilitiesRevamp
main: org.mcplugindev.foxutilities.FoxUtilitiesRevamp
version: 1.0
description: 'FoxUtilitesCore Revamped'
author: FoxIshDaBest

commands:
    fur:
      description: 'Displays FoxUtilitiesRevamp information.'
      usage: /<command>
      alias: [foxutilitiesrevamp]
        
    getip:
        description: 'Get a player''s IP address.'
        usage: /<command>
        
    getgamemode:
        description: 'Get a player''s current gamemode.'
        usage: /<command>
        alias: [ggm]

